version: "3.8"
services:
  echo-service:
    build: 
      context: .
      target: ${BUILD_TARGET:-runner}
    ports:
      - "${PORT:-3000}:${PORT:-3000}"
    environment:
      - NODE_ENV=${NODE_ENV:-development}
      - PORT=${PORT:-3000}
      - npm_package_version=${npm_package_version:-1.0.0}
      - SOURCE_CODE=https://github.com/junjie-w/echo-service
      - SERVICE_NAME=echo-service
      - HUSKY=1
    healthcheck:
      test: [CMD, wget, --spider, -q, "http://localhost:${PORT:-3000}/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    volumes:
      - .:/app:delegated
      - /app/node_modules
      - /app/dist
